<a href="https://colab.research.google.com/github/czyz-patryk/dataScience/blob/main/keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


'2.9.2'

In [8]:
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)

In [9]:
from tensorflow.keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,)))

In [10]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 4)                 44        
                                                                 
Total params: 44
Trainable params: 44
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.add(Dense(units=2))

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 4)                 44        
                                                                 
 dense_3 (Dense)             (None, 2)                 10        
                                                                 
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________


In [13]:
from tensorflow.keras.activations import linear 

random_data = np.linspace(start=-3, stop=3, num=300)
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [14]:
px.line(data, x='data', y='linear', width=500, height=400, range_y=[-3, 3])

In [15]:
from tensorflow.keras.activations import sigmoid 

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [16]:
px.line(data, x='data', y='sigmoid', width=500, height=400, range_y=[-0.5, 1.5])

In [17]:
from tensorflow.keras.activations import relu 

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()

data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0

In [18]:
px.line(data, x='data', y='relu', width=500, height=400, range_y=[-0.5, 1.5])

In [19]:
from tensorflow.keras.activations import tanh 

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()

data      tanh
0 -3.000000 -0.995055
1 -2.979933 -0.994853
2 -2.959866 -0.994643
3 -2.939799 -0.994424
4 -2.919732 -0.994196

In [21]:
px.line(data, x='data', y='tanh', width=500, height=400, range_y=[-1.5, 1.5])

In [23]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 8)                 88        
                                                                 
 dense_5 (Dense)             (None, 1)                 9         
                                                                 
Total params: 97
Trainable params: 97
Non-trainable params: 0
_________________________________________________________________


In [24]:
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.compile(optimizer='rmsprop',
              loss='mse')

In [25]:
# model.fit(data, labels, epochs=10, batch_size=32)

In [26]:
data = np.random.randn(10000, 150)
labels = np.random.randint(2, size=(10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [ ]:
data[:3]

In [28]:
labels[:10]

array([[1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0]])

In [29]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
313/313 [==============================] - 3s 2ms/step - loss: 0.7580 - accuracy: 0.5019
Epoch 2/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6969 - accuracy: 0.5495
Epoch 3/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6753 - accuracy: 0.5814
Epoch 4/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6583 - accuracy: 0.6085
Epoch 5/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6436 - accuracy: 0.6312
Epoch 6/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6299 - accuracy: 0.6513
Epoch 7/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6156 - accuracy: 0.6671
Epoch 8/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6025 - accuracy: 0.6855
Epoch 9/20
313/313 [==============================] - 1s 2ms/step - loss: 0.5891 - accuracy: 0.6931
Epoch 10/20
313/313 [==============================] - 1s 2ms/step - loss: 0.5765 - accuracy: 0.7037

In [31]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=64)

Epoch 1/20
157/157 [==============================] - 1s 3ms/step - loss: 0.7885 - accuracy: 0.5001
Epoch 2/20
157/157 [==============================] - 0s 3ms/step - loss: 0.7041 - accuracy: 0.5332
Epoch 3/20
157/157 [==============================] - 0s 3ms/step - loss: 0.6853 - accuracy: 0.5577
Epoch 4/20
157/157 [==============================] - 1s 3ms/step - loss: 0.6726 - accuracy: 0.5810
Epoch 5/20
157/157 [==============================] - 0s 3ms/step - loss: 0.6621 - accuracy: 0.5997
Epoch 6/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6520 - accuracy: 0.6162
Epoch 7/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6425 - accuracy: 0.6341
Epoch 8/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6330 - accuracy: 0.6447
Epoch 9/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6229 - accuracy: 0.6635
Epoch 10/20
157/157 [==============================] - 0s 2ms/step - loss: 0.6128 - accuracy: 0.6732

In [32]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=64, validation_split=0.2)

Epoch 1/20
125/125 [==============================] - 2s 9ms/step - loss: 0.7609 - accuracy: 0.5038 - val_loss: 0.7233 - val_accuracy: 0.5080
Epoch 2/20
125/125 [==============================] - 0s 2ms/step - loss: 0.7030 - accuracy: 0.5309 - val_loss: 0.7122 - val_accuracy: 0.5085
Epoch 3/20
125/125 [==============================] - 0s 3ms/step - loss: 0.6841 - accuracy: 0.5580 - val_loss: 0.7111 - val_accuracy: 0.5080
Epoch 4/20
125/125 [==============================] - 0s 2ms/step - loss: 0.6715 - accuracy: 0.5856 - val_loss: 0.7099 - val_accuracy: 0.5130
Epoch 5/20
125/125 [==============================] - 0s 3ms/step - loss: 0.6607 - accuracy: 0.6010 - val_loss: 0.7114 - val_accuracy: 0.5090
Epoch 6/20
125/125 [==============================] - 0s 2ms/step - loss: 0.6503 - accuracy: 0.6205 - val_loss: 0.7136 - val_accuracy: 0.5170
Epoch 7/20
125/125 [==============================] - 1s 4ms/step - loss: 0.6401 - accuracy: 0.6344 - val_loss: 0.7169 - val_accuracy: 0.5245
Epoch 

In [34]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])
history = model.fit(data, labels, epochs=20, batch_size=64, validation_split=0.2, verbose=0)
history

In [36]:
metrics = history.history
metrics.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [37]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])
history = model.fit(data, labels, epochs=20, batch_size=64, validation_split=0.2, verbose=1)
history

Epoch 1/20
125/125 [==============================] - 1s 4ms/step - loss: 0.7605 - accuracy: 0.5020 - val_loss: 0.7397 - val_accuracy: 0.4945
Epoch 2/20
125/125 [==============================] - 0s 3ms/step - loss: 0.7046 - accuracy: 0.5357 - val_loss: 0.7319 - val_accuracy: 0.4945
Epoch 3/20
125/125 [==============================] - 1s 4ms/step - loss: 0.6848 - accuracy: 0.5631 - val_loss: 0.7309 - val_accuracy: 0.4940
Epoch 4/20
125/125 [==============================] - 0s 4ms/step - loss: 0.6704 - accuracy: 0.5865 - val_loss: 0.7326 - val_accuracy: 0.4835
Epoch 5/20
125/125 [==============================] - 0s 3ms/step - loss: 0.6582 - accuracy: 0.6080 - val_loss: 0.7352 - val_accuracy: 0.4825
Epoch 6/20
125/125 [==============================] - 1s 5ms/step - loss: 0.6467 - accuracy: 0.6255 - val_loss: 0.7362 - val_accuracy: 0.4915
Epoch 7/20
125/125 [==============================] - 1s 4ms/step - loss: 0.6349 - accuracy: 0.6450 - val_loss: 0.7410 - val_accuracy: 0.4920
Epoch 

In [38]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [39]:
model.predict(test_data)

1/1 [==============================] - 0s 170ms/step


array([[0.19870077],
       [0.49473515],
       [0.42546335],
       [0.37724438],
       [0.81000894]], dtype=float32)

In [41]:
model.predict(test_data)

1/1 [==============================] - 0s 41ms/step


array([[0.19870077],
       [0.49473515],
       [0.42546335],
       [0.37724438],
       [0.81000894]], dtype=float32)

In [45]:
predictions = (model.predict(test_data) > 0.5).astype("int32")
predictions

1/1 [==============================] - 0s 39ms/step


array([[0],
       [0],
       [0],
       [0],
       [1]], dtype=int32)

In [46]:
data = np.random.random((10000, 150))
labels = np.random.randint(10, size=(10000, 1))

In [47]:
print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [48]:
labels[:10]

array([[9],
       [0],
       [8],
       [0],
       [8],
       [1],
       [8],
       [6],
       [9],
       [0]])

In [50]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], dtype=float32)

In [51]:
labels[1]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [53]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, batch_size=32, epochs=30, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 3s 4ms/step - loss: 2.3136 - accuracy: 0.0991 - val_loss: 2.3029 - val_accuracy: 0.1015
Epoch 2/30
250/250 [==============================] - 1s 2ms/step - loss: 2.3025 - accuracy: 0.1077 - val_loss: 2.3045 - val_accuracy: 0.1045
Epoch 3/30
250/250 [==============================] - 1s 2ms/step - loss: 2.3015 - accuracy: 0.1119 - val_loss: 2.3054 - val_accuracy: 0.1020
Epoch 4/30
250/250 [==============================] - 1s 2ms/step - loss: 2.2998 - accuracy: 0.1128 - val_loss: 2.3056 - val_accuracy: 0.0990
Epoch 5/30
250/250 [==============================] - 1s 3ms/step - loss: 2.2972 - accuracy: 0.1157 - val_loss: 2.3067 - val_accuracy: 0.0990
Epoch 6/30
250/250 [==============================] - 1s 4ms/step - loss: 2.2957 - accuracy: 0.1225 - val_loss: 2.3114 - val_accuracy: 0.1035
Epoch 7/30
250/250 [==============================] - 1s 4ms/step - loss: 2.2930 - accuracy: 0.1201 - val_loss: 2.3083 - val_accuracy: 0.1055
Epoch 

In [54]:
test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 [==============================] - 0s 81ms/step


array([[0.09729904, 0.05172775, 0.09698205, 0.07667124, 0.07050946,
        0.06680733, 0.06019173, 0.24971399, 0.05355409, 0.17654324],
       [0.06758527, 0.09812563, 0.07275634, 0.11982478, 0.11874932,
        0.18221088, 0.07029321, 0.09233182, 0.02930735, 0.14881532],
       [0.1032877 , 0.0833976 , 0.13958079, 0.10124706, 0.08211005,
        0.10881612, 0.093266  , 0.14610144, 0.05487397, 0.08731923],
       [0.07276033, 0.1052445 , 0.11686159, 0.10339907, 0.08891889,
        0.09714951, 0.07400119, 0.19163431, 0.04815464, 0.10187587],
       [0.13110368, 0.04446582, 0.13445292, 0.04797621, 0.06236419,
        0.05317141, 0.17478222, 0.05880629, 0.25262892, 0.0402483 ],
       [0.05201304, 0.0816365 , 0.10980705, 0.0927968 , 0.12772644,
        0.06732035, 0.18156071, 0.10950527, 0.08542787, 0.09220599],
       [0.10171454, 0.09286013, 0.09787025, 0.08122046, 0.08435319,
        0.10496303, 0.10596861, 0.133301  , 0.06811968, 0.12962922],
       [0.20383978, 0.08810654, 0.1084436

In [61]:
model.predict_on_batch(test_data)

array([[0.09729904, 0.05172775, 0.09698205, 0.07667124, 0.07050946,
        0.06680733, 0.06019173, 0.24971399, 0.05355409, 0.17654324],
       [0.06758527, 0.09812563, 0.07275634, 0.11982478, 0.11874932,
        0.18221088, 0.07029321, 0.09233182, 0.02930735, 0.14881532],
       [0.1032877 , 0.0833976 , 0.13958079, 0.10124706, 0.08211005,
        0.10881612, 0.093266  , 0.14610144, 0.05487397, 0.08731923],
       [0.07276033, 0.1052445 , 0.11686159, 0.10339907, 0.08891889,
        0.09714951, 0.07400119, 0.19163431, 0.04815464, 0.10187587],
       [0.13110368, 0.04446582, 0.13445292, 0.04797621, 0.06236419,
        0.05317141, 0.17478222, 0.05880629, 0.25262892, 0.0402483 ],
       [0.05201304, 0.0816365 , 0.10980705, 0.0927968 , 0.12772644,
        0.06732035, 0.18156071, 0.10950527, 0.08542787, 0.09220599],
       [0.10171454, 0.09286013, 0.09787025, 0.08122046, 0.08435319,
        0.10496303, 0.10596861, 0.133301  , 0.06811968, 0.12962922],
       [0.20383978, 0.08810654, 0.1084436

In [73]:
data = np.random.random((10000, 150))
labels = 50 * np.random.random(10000)

In [74]:
labels[:10]

array([ 3.35335444, 27.58112323, 47.8787837 , 21.14774392,  2.51517771,
       31.44747407, 16.36321721, 25.59004822, 24.75507449, 33.84058175])

In [75]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 1s 2ms/step - loss: 256.0287 - val_loss: 209.7764
Epoch 2/30
250/250 [==============================] - 1s 2ms/step - loss: 207.2499 - val_loss: 211.0093
Epoch 3/30
250/250 [==============================] - 1s 2ms/step - loss: 207.0249 - val_loss: 209.9669
Epoch 4/30
250/250 [==============================] - 0s 2ms/step - loss: 206.5285 - val_loss: 209.8071
Epoch 5/30
250/250 [==============================] - 0s 2ms/step - loss: 206.2261 - val_loss: 210.6322
Epoch 6/30
250/250 [==============================] - 1s 2ms/step - loss: 205.8356 - val_loss: 210.0656
Epoch 7/30
250/250 [==============================] - 1s 2ms/step - loss: 205.5744 - val_loss: 210.9802
Epoch 8/30
250/250 [==============================] - 1s 2ms/step - loss: 205.3982 - val_loss: 210.4042
Epoch 9/30
250/250 [==============================] - 1s 3ms/step - loss: 205.1246 - val_loss: 210.2664
Epoch 10/30
250/250 [==============================] - 1s 3ms/st

In [76]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, batch_size=32, epochs=30, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 2s 5ms/step - loss: 13.5037 - mse: 257.0789 - val_loss: 12.4881 - val_mse: 209.5555
Epoch 2/30
250/250 [==============================] - 1s 3ms/step - loss: 12.4635 - mse: 207.6737 - val_loss: 12.5014 - val_mse: 209.9112
Epoch 3/30
250/250 [==============================] - 1s 3ms/step - loss: 12.4455 - mse: 207.0382 - val_loss: 12.4856 - val_mse: 209.5381
Epoch 4/30
250/250 [==============================] - 1s 3ms/step - loss: 12.4357 - mse: 206.8536 - val_loss: 12.5303 - val_mse: 210.8598
Epoch 5/30
250/250 [==============================] - 1s 3ms/step - loss: 12.4151 - mse: 206.5916 - val_loss: 12.4783 - val_mse: 209.5455
Epoch 6/30
250/250 [==============================] - 1s 3ms/step - loss: 12.3992 - mse: 206.1488 - val_loss: 12.5404 - val_mse: 211.3087
Epoch 7/30
250/250 [==============================] - 1s 3ms/step - loss: 12.3807 - mse: 206.2625 - val_loss: 12.5207 - val_mse: 213.5662
Epoch 8/30
250/250 [==============

In [77]:
test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 [==============================] - 0s 92ms/step


array([[25.076097],
       [27.318869],
       [26.318863],
       [23.74363 ],
       [22.210146],
       [28.435759],
       [26.641903],
       [24.845987],
       [25.678698],
       [26.866457]], dtype=float32)