<a href="https://colab.research.google.com/github/czyz-patryk/dataScience/blob/main/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
v1 = np.array([0, 4])
v1

array([0, 4])

In [4]:
np.linalg.norm(v1)

4.0

In [6]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

Odległość punktów na płaszczyźnie

In [7]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

In [8]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

Mnożenie macierzy

In [10]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [11]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [12]:
Z.shape

(2, 1)

In [13]:
X = np.array([[2, -1, 3], 
              [3, 1, 0]])
Y = np.array([[2, 1, -1], 
              [0, -1, 2], 
              [3, 2, 0]])

print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [16]:
Z = np.dot(X, Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

Wyznacznik macierzy

In [18]:
A = np.array([[2, 4], 
              [-1, 3]])

round(np.linalg.det(A))

10

Ślad macierzy

In [19]:
np.trace(A)

5

Macierz jednostkowa

In [20]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Macierz odwrotna

In [22]:
A = np.array([[2, 4], 
              [-1, 3]])

B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [24]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [25]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

Macierz transponowana

In [26]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [29]:
A = np.array([[2, 4], 
              [1, -1]])
print(A)

B = np.array([[10], [-1]])
print(B)

[[ 2  4]
 [ 1 -1]]
[[10]
 [-1]]


In [32]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [33]:
X.shape

(2, 1)