<a href="https://colab.research.google.com/github/czyz-patryk/dataScience/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.21.6'

In [2]:
x = np.array([1, 3])
x

array([1, 3])

In [3]:
print(x)

[1 3]


In [4]:
type(x)

numpy.ndarray

In [5]:
x.ndim

1

In [6]:
x.shape

(2,)

In [7]:
x.size

2

In [8]:
x.dtype

dtype('int64')

In [9]:
y = np.array([1.3, 2.3, 1.4])
print(y)

[1.3 2.3 1.4]


In [10]:
y.dtype

dtype('float64')

In [11]:
z = np.array([[1, 2], [-3, 1]])

In [12]:
z.ndim

2

In [13]:
z.shape

(2, 2)

In [14]:
z.size

4

In [15]:
a = np.array([[1, 2, 3], [4, 2, 1]])
print(a)

[[1 2 3]
 [4 2 1]]


In [16]:
a.shape

(2, 3)

In [17]:
b = np.array(
    [
      [[2, 5, 2], [4, 2, 6]],
     
      [[7, 3, 3], [4, 7, 2]],
     
     [[7, 3, 3], [4, 7, 2]]
    ]
    )
print(b)

[[[2 5 2]
  [4 2 6]]

 [[7 3 3]
  [4 7 2]]

 [[7 3 3]
  [4 7 2]]]


In [18]:
b.ndim

3

In [19]:
b.shape

(3, 2, 3)

In [20]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [21]:
B = np.array([1, 2, 3], dtype='complex')
B.dtype

dtype('complex128')

In [22]:
C = np.array([True, False])
C.dtype

dtype('bool')

In [23]:
D = np.array([24, 120, 230], dtype=np.int8)
D.dtype

dtype('int8')

In [24]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [25]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [29]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [30]:
np.arange(start=200, stop=5, step=-15)

array([200, 185, 170, 155, 140, 125, 110,  95,  80,  65,  50,  35,  20])

In [31]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [32]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [33]:
E = np.arange(15)
E

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
E.reshape(3, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
np.random.seed(0)

In [36]:
np.random.randn(10)

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [37]:
np.random.randn(10, 4)

array([[ 0.14404357,  1.45427351,  0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982,  0.6536186 ],
       [ 0.8644362 , -0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  1.20237985],
       [-0.38732682, -0.30230275, -1.04855297, -1.42001794],
       [-1.70627019,  1.9507754 , -0.50965218, -0.4380743 ],
       [-1.25279536,  0.77749036, -1.61389785, -0.21274028]])

In [38]:
np.random.randint(10)

7

In [39]:
np.random.randint(low=10, high=101, size=10)

array([89, 23, 95, 58, 59, 79, 51, 45, 74, 79])

In [40]:
np.random.choice([4, 1, 3, 2])

3

In [41]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.random.shuffle(data)

In [43]:
data

array([3, 6, 5, 8, 9, 7, 4, 2, 1, 0])

In [44]:
np.exp(1)

2.718281828459045

In [45]:
np.sqrt(9)

3.0

In [46]:
np.all([2, 3, 1])

True

In [47]:
np.all([2, 0, 1])

False

In [48]:
np.any([2, 3, 1])

True

In [49]:
np.all([0, 0, 0])

False

In [50]:
A = np.random.rand(5)
A

array([0.97676109, 0.60484552, 0.73926358, 0.03918779, 0.28280696])

In [51]:
np.argmax(A)

0

In [52]:
A[np.argmax(A)]

0.9767610881903371

In [53]:
np.argmin(A)

3

In [54]:
A[np.argmin(A)]

0.039187792254320675

In [55]:
np.argsort(A)

array([3, 4, 1, 2, 0])

In [56]:
np.max(A)

0.9767610881903371

In [57]:
np.min(A)

0.039187792254320675

In [58]:
np.mean(A)

0.528572988432883

In [59]:
np.median(A)

0.604845519745046

In [60]:
np.std(A)

0.33195764989598736

In [64]:
A = np.arange(20)
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [65]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [67]:
for row in A:
  print(row[:3])

[0 1 2]
[5 6 7]
[10 11 12]
[15 16 17]


In [69]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [70]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [72]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [73]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [79]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [80]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [81]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [82]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [83]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [84]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [85]:
A[np.bitwise_or(A < -5, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])